apiVersion: v1
kind: Pod
metadata:
  name: sailorpod
spec:
  containers: 
  - name: sailorcon
    image: #specify image
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - name: TomcatPort
        containerPort: 8080
        protocol: TCP